from .binary_elementwise_spec import BinaryElementwiseSpec
from .fold_spec import FoldSpec
from .group_spec import GroupSpec
from .op_spec import OpSpec
from .pad_spec import PadSpec
from .permute_spec import PermuteSpec
from .reduce_spec import ReduceSpec
from .repeat_spec import RepeatSpec
from .select_spec import SelectSpec
from .slice_spec import SliceSpec
from .squeeze_spec import SqueezeSpec
from .unary_elementwise_spec import UnaryElementwiseSpec
from .unfold_spec import UnfoldSpec
from .ungroup_spec import UngroupSpec
from .unsqueeze_spec import UnsqueezeSpec
